services:
  fitness-app:
    build: .
    ports:
      - "5000:5000"
    labels:
      com.datadoghq.ad.logs: '[{"source":"nodejs","service":"fitness-tracker"}]'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/fitness-tracker
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
      - DD_SERVICE=fitness-tracker
      - DD_ENV=production
      - DD_VERSION=1.0.0
      - DD_LOGS_INJECTION=true
    depends_on:
      - mongodb
      - datadog-agent

  mongodb:
    image: mongo:7.0-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    environment:
      - DD_API_KEY=17f70c28759e381392e0f9efd594582b
      - DD_SITE=datadoghq.com
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

volumes:
  mongodb_data:
